# Generated by Django 4.2 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_date',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(default='2000-01-01', max_length=200),
            preserve_default=False,
        ),
    ]
